apiVersion: v1
kind: Service
metadata:
  name: http-aap-service
  namespace: red
spec:
  selector:
    app: http-aap
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: LoadBalancer 
