apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-sa
  labels: 
    app: pod-nginx-sa
  namespace: blue
spec:
  serviceAccountName: blue-sa
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80