apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-redactor-binding
  namespace: blue
subjects:
- kind: ServiceAccount
  name: blue-sa
  namespace: blue
roleRef:
  kind: Role
  name: pod-redactor
  apiGroup: rbac.authorization.k8s.io