apiVersion: v1
kind: Service
metadata:
  name: nodeport-myapp
  namespace: blue
spec:
  type: NodePort
  selector:
    app: my-aap
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      