apiVersion: v1
kind: Service
metadata:
  name: clusterip-nginx
  namespace: blue
spec:
  type: ClusterIP
  selector:
    app: pod-nginx-sa
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80