apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-aap
  namespace: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-aap
  template:
    metadata:
      labels:
        app: my-aap
    spec:
      containers:
      - name: my-aap
        image: alex1436183/my-app
        ports:
        - containerPort: 5000
