apiVersion: v1
kind: Service
metadata:
  name: my-aap
  namespace: blue
spec:
  selector:
    app: my-aap
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer 
