version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  web1:
    build:
      context: .
    ports:
      - "5001:80"
    depends_on:
      - db
    links:
      - db
volumes:
  db_data:
