---
- name: Install Nginx on servers
  hosts: all
  become: true  # Запускае команды через sudo 


  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian" # если у нас используются разные операционки то будет выполнена только Ubuntu/Debian

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: true
